site_name: Yiri OneBot Documents
repo_name: YiriMiraiProject/YiriOneBot
repo_url: https://github.com/YiriMiraiProject/YiriOneBot
site_url: https://docs.yiri-.online/
copyright: 版权所有 &copy; 2024 YiriMiraiProject 项目组成员和其他贡献者

theme:
  name: material
  font: false
  features:
    - search.suggest
    - search.highlight

    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer

    - content.code.copy
    - content.code.select

    # - toc.integrate

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 欢迎: index.md
  - 快速上手: getting-started.md
  - 基础:
      - 关于 Bot 对象: basic/about-bot-object.md
      - 异步编程: basic/async-programming.md
